spring.application.name=understory_back
spring.config.import=file:env.properties
# SERVER CONFIG
server.port=${PORT}
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#JWT
jwt.secret=${jwt_secret}
# CLOUDINARY
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
#MAILGUN
# MAIL GUN
mailgun.api.key=${MG_API_KEY}
mailgun.domain=${MG_DOMAIN}
mailgun.from=${MG_EMAIL}
mailgun.baseurl=https://api.mailgun.net
# SEED ADMIN
seed.superadmin.email=${SEED_SUPERADMIN_EMAIL}
seed.superadmin.password=${SEED_SUPERADMIN_PASSWORD}
seed.admin.one.email=${SEED_ADMIN_ONE_EMAIL}
seed.admin.one.password=${SEED_ADMIN_ONE_PASSWORD}
seed.admin.two.email=${SEED_ADMIN_TWO_EMAIL}
seed.admin.two.password=${SEED_ADMIN_TWO_PASSWORD}
seed.admin.three.email=${SEED_ADMIN_THREE_EMAIL}
seed.admin.three.password=${SEED_ADMIN_THREE_PASSWORD}